version: '3'

services:

  docker-mysql:
    container_name: hisebnikash-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345671
    networks:
      - my_mysql_net
    ports:
      - 3306:3306
#
  springboot-docker-compose-hisebnikash-container:
    image: springboot-docker-compose-hisebnikash-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    depends_on:
      - docker-mysql
    links:
      - docker-mysql:mysql
    networks:
      - my_mysql_net
    environment:
      - MYSQL_HOST=docker-mysql

networks:
  my_mysql_net:
    driver: bridge


